version: "3.8"
services:
  polkadot:
    image: docker.io/parity/polkadot:latest
    user: root
    command: '--name my-westend-instance --chain westend --base-path /data --database rocksdb --unsafe-ws-external --rpc-cors all --rpc-external --prometheus-external'
    container_name: polkadot
    restart: unless-stopped
    volumes:
      - /data:/data
    ports:
      - "30333:30333"
      - "9615:9615"
      #- "127.0.0.1:9933:9933"
      - "9933:9933"
      #- "127.0.0.1:9944:9944"
      - "9944:9944"
    networks:
      - dot
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  sidecar:
    #image: docker.io/parity/substrate-api-sidecar:v11.0.0
    build:
      context: sidecar
    user: root
    container_name: sidecar
    restart: always
    ports:
       #- "127.0.0.1:8080:8080"
       - "8080:8080"
    environment:
      SAS_SUBSTRATE_WS_URL: ws://polkadot:9944
    networks:
      - dot
    depends_on:
      - polkadot
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  dot:
    name: dot
